// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/port/pb.proto

/*
Package port is a generated protocol buffer package.

It is generated from these files:
	pb/port/pb.proto

It has these top-level messages:
	SavePortRequest
	SavePortResponse
	GetPortsRequest
	GetPortsResponse
	PortEntity
*/
package port

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/lyft/protoc-gen-validate/validate"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PortDomainServiceErrorCode int32

const (
	PortDomainServiceErrorCode_Unknown        PortDomainServiceErrorCode = 0
	PortDomainServiceErrorCode_Internal       PortDomainServiceErrorCode = 5000
	PortDomainServiceErrorCode_InvalidRequest PortDomainServiceErrorCode = 4000
)

var PortDomainServiceErrorCode_name = map[int32]string{
	0:    "Unknown",
	5000: "Internal",
	4000: "InvalidRequest",
}
var PortDomainServiceErrorCode_value = map[string]int32{
	"Unknown":        0,
	"Internal":       5000,
	"InvalidRequest": 4000,
}

func (x PortDomainServiceErrorCode) String() string {
	return proto.EnumName(PortDomainServiceErrorCode_name, int32(x))
}
func (PortDomainServiceErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SavePortRequest struct {
	Port *PortEntity `protobuf:"bytes,1,opt,name=Port" json:"Port,omitempty"`
}

func (m *SavePortRequest) Reset()                    { *m = SavePortRequest{} }
func (m *SavePortRequest) String() string            { return proto.CompactTextString(m) }
func (*SavePortRequest) ProtoMessage()               {}
func (*SavePortRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SavePortRequest) GetPort() *PortEntity {
	if m != nil {
		return m.Port
	}
	return nil
}

type SavePortResponse struct {
}

func (m *SavePortResponse) Reset()                    { *m = SavePortResponse{} }
func (m *SavePortResponse) String() string            { return proto.CompactTextString(m) }
func (*SavePortResponse) ProtoMessage()               {}
func (*SavePortResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetPortsRequest struct {
	Limit  uint64 `protobuf:"varint,1,opt,name=Limit" json:"Limit,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=Offset" json:"Offset,omitempty"`
}

func (m *GetPortsRequest) Reset()                    { *m = GetPortsRequest{} }
func (m *GetPortsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPortsRequest) ProtoMessage()               {}
func (*GetPortsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetPortsRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetPortsRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetPortsResponse struct {
	Items []*PortEntity `protobuf:"bytes,1,rep,name=Items" json:"Items,omitempty"`
}

func (m *GetPortsResponse) Reset()                    { *m = GetPortsResponse{} }
func (m *GetPortsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPortsResponse) ProtoMessage()               {}
func (*GetPortsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetPortsResponse) GetItems() []*PortEntity {
	if m != nil {
		return m.Items
	}
	return nil
}

type PortEntity struct {
}

func (m *PortEntity) Reset()                    { *m = PortEntity{} }
func (m *PortEntity) String() string            { return proto.CompactTextString(m) }
func (*PortEntity) ProtoMessage()               {}
func (*PortEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*SavePortRequest)(nil), "port.SavePortRequest")
	proto.RegisterType((*SavePortResponse)(nil), "port.SavePortResponse")
	proto.RegisterType((*GetPortsRequest)(nil), "port.GetPortsRequest")
	proto.RegisterType((*GetPortsResponse)(nil), "port.GetPortsResponse")
	proto.RegisterType((*PortEntity)(nil), "port.PortEntity")
	proto.RegisterEnum("port.PortDomainServiceErrorCode", PortDomainServiceErrorCode_name, PortDomainServiceErrorCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PortDomainService service

type PortDomainServiceClient interface {
	SavePort(ctx context.Context, in *SavePortRequest, opts ...grpc.CallOption) (*SavePortResponse, error)
	GetPorts(ctx context.Context, in *GetPortsRequest, opts ...grpc.CallOption) (*GetPortsResponse, error)
}

type portDomainServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortDomainServiceClient(cc *grpc.ClientConn) PortDomainServiceClient {
	return &portDomainServiceClient{cc}
}

func (c *portDomainServiceClient) SavePort(ctx context.Context, in *SavePortRequest, opts ...grpc.CallOption) (*SavePortResponse, error) {
	out := new(SavePortResponse)
	err := grpc.Invoke(ctx, "/port.PortDomainService/SavePort", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portDomainServiceClient) GetPorts(ctx context.Context, in *GetPortsRequest, opts ...grpc.CallOption) (*GetPortsResponse, error) {
	out := new(GetPortsResponse)
	err := grpc.Invoke(ctx, "/port.PortDomainService/GetPorts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PortDomainService service

type PortDomainServiceServer interface {
	SavePort(context.Context, *SavePortRequest) (*SavePortResponse, error)
	GetPorts(context.Context, *GetPortsRequest) (*GetPortsResponse, error)
}

func RegisterPortDomainServiceServer(s *grpc.Server, srv PortDomainServiceServer) {
	s.RegisterService(&_PortDomainService_serviceDesc, srv)
}

func _PortDomainService_SavePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortDomainServiceServer).SavePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/port.PortDomainService/SavePort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortDomainServiceServer).SavePort(ctx, req.(*SavePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortDomainService_GetPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortDomainServiceServer).GetPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/port.PortDomainService/GetPorts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortDomainServiceServer).GetPorts(ctx, req.(*GetPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PortDomainService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "port.PortDomainService",
	HandlerType: (*PortDomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SavePort",
			Handler:    _PortDomainService_SavePort_Handler,
		},
		{
			MethodName: "GetPorts",
			Handler:    _PortDomainService_GetPorts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/port/pb.proto",
}

func init() { proto.RegisterFile("pb/port/pb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0xdb, 0xff, 0x6f, 0x6b, 0xb9, 0x55, 0x3b, 0x8e, 0x5a, 0x4b, 0x37, 0xca, 0x20, 0x2a,
	0x2e, 0x5a, 0xa8, 0x0b, 0x41, 0x17, 0x82, 0x5a, 0x24, 0xa0, 0x28, 0x29, 0x6e, 0xdc, 0x25, 0xf6,
	0x16, 0x06, 0x9b, 0x99, 0x38, 0x33, 0x46, 0x7c, 0x03, 0x37, 0xbe, 0x83, 0x8f, 0x6a, 0x27, 0x93,
	0x21, 0x10, 0xdd, 0xe5, 0x9c, 0x9b, 0xf3, 0x31, 0xf7, 0x5c, 0x20, 0x69, 0x3c, 0x4a, 0xa5, 0x32,
	0xa3, 0x34, 0x1e, 0xa6, 0x4a, 0x1a, 0x49, 0x1b, 0x56, 0x0e, 0x76, 0xb2, 0x68, 0xc1, 0x67, 0x91,
	0xc1, 0x91, 0xff, 0x70, 0x63, 0x76, 0x0a, 0xdd, 0x69, 0x94, 0xe1, 0xc3, 0xf2, 0xa7, 0x10, 0x5f,
	0xdf, 0x50, 0x1b, 0xba, 0x0f, 0x0d, 0x2b, 0xfb, 0xf5, 0xbd, 0xfa, 0x51, 0x67, 0x4c, 0x86, 0x16,
	0x30, 0xb4, 0xce, 0x44, 0x18, 0x6e, 0x3e, 0xc2, 0x7c, 0xca, 0x28, 0x90, 0x32, 0xa8, 0x53, 0x29,
	0x34, 0xb2, 0x0b, 0xe8, 0xde, 0xa0, 0xb1, 0x96, 0xf6, 0xb0, 0x2d, 0x68, 0xde, 0xf2, 0x84, 0x3b,
	0x5a, 0x23, 0x74, 0x82, 0xf6, 0xa0, 0x75, 0x3f, 0x9f, 0x6b, 0x34, 0xfd, 0x7f, 0xb9, 0x5d, 0x28,
	0x76, 0x06, 0xa4, 0x04, 0x38, 0x28, 0x3d, 0x80, 0x66, 0x60, 0x30, 0xd1, 0x4b, 0xc2, 0xff, 0x3f,
	0xdf, 0xe3, 0xc6, 0x6c, 0x15, 0xa0, 0x34, 0x8f, 0xef, 0x60, 0x60, 0xd5, 0xb5, 0x4c, 0x22, 0x2e,
	0xa6, 0xa8, 0x32, 0xfe, 0x8c, 0x13, 0xa5, 0xa4, 0xba, 0x92, 0x33, 0xa4, 0x1d, 0x58, 0x79, 0x14,
	0x2f, 0x42, 0xbe, 0x0b, 0x52, 0xa3, 0x6b, 0xd0, 0x0e, 0x84, 0x41, 0x25, 0xa2, 0x05, 0xf9, 0x3c,
	0xa4, 0x9b, 0xb0, 0x1e, 0x88, 0xbc, 0xa5, 0x62, 0x07, 0xf2, 0xbd, 0x3b, 0xfe, 0xaa, 0xc3, 0xc6,
	0x2f, 0x1e, 0x3d, 0x87, 0xb6, 0xef, 0x80, 0x6e, 0xbb, 0x77, 0x55, 0xca, 0x1c, 0xf4, 0xaa, 0x76,
	0x51, 0x55, 0xcd, 0x86, 0xfd, 0xae, 0x3e, 0x5c, 0x29, 0xcf, 0x87, 0xab, 0x95, 0xb0, 0xda, 0x65,
	0xeb, 0x29, 0xbf, 0x6b, 0xdc, 0xca, 0xaf, 0x78, 0xf2, 0x13, 0x00, 0x00, 0xff, 0xff, 0xda, 0x14,
	0xe5, 0xb1, 0xf8, 0x01, 0x00, 0x00,
}
