// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pb/port/pb.proto

package port

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on FindAllPortsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *FindAllPortsRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Limit

	// no validation rules for Offset

	return nil
}

// FindAllPortsRequestValidationError is the validation error returned by
// FindAllPortsRequest.Validate if the designated constraints aren't met.
type FindAllPortsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FindAllPortsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FindAllPortsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FindAllPortsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FindAllPortsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FindAllPortsRequestValidationError) ErrorName() string {
	return "FindAllPortsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FindAllPortsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFindAllPortsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FindAllPortsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FindAllPortsRequestValidationError{}

// Validate checks the field values on FindAllPortsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *FindAllPortsResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FindAllPortsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// FindAllPortsResponseValidationError is the validation error returned by
// FindAllPortsResponse.Validate if the designated constraints aren't met.
type FindAllPortsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FindAllPortsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FindAllPortsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FindAllPortsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FindAllPortsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FindAllPortsResponseValidationError) ErrorName() string {
	return "FindAllPortsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e FindAllPortsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFindAllPortsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FindAllPortsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FindAllPortsResponseValidationError{}

// Validate checks the field values on SavePortRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *SavePortRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPort() == nil {
		return SavePortRequestValidationError{
			field:  "Port",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetPort()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SavePortRequestValidationError{
				field:  "Port",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// SavePortRequestValidationError is the validation error returned by
// SavePortRequest.Validate if the designated constraints aren't met.
type SavePortRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SavePortRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SavePortRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SavePortRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SavePortRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SavePortRequestValidationError) ErrorName() string { return "SavePortRequestValidationError" }

// Error satisfies the builtin error interface
func (e SavePortRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSavePortRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SavePortRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SavePortRequestValidationError{}

// Validate checks the field values on SavePortResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *SavePortResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// SavePortResponseValidationError is the validation error returned by
// SavePortResponse.Validate if the designated constraints aren't met.
type SavePortResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SavePortResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SavePortResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SavePortResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SavePortResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SavePortResponseValidationError) ErrorName() string { return "SavePortResponseValidationError" }

// Error satisfies the builtin error interface
func (e SavePortResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSavePortResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SavePortResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SavePortResponseValidationError{}

// Validate checks the field values on SavePortsBulkRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *SavePortsBulkRequest) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SavePortsBulkRequestValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// SavePortsBulkRequestValidationError is the validation error returned by
// SavePortsBulkRequest.Validate if the designated constraints aren't met.
type SavePortsBulkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SavePortsBulkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SavePortsBulkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SavePortsBulkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SavePortsBulkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SavePortsBulkRequestValidationError) ErrorName() string {
	return "SavePortsBulkRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SavePortsBulkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSavePortsBulkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SavePortsBulkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SavePortsBulkRequestValidationError{}

// Validate checks the field values on SavePortsBulkResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *SavePortsBulkResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// SavePortsBulkResponseValidationError is the validation error returned by
// SavePortsBulkResponse.Validate if the designated constraints aren't met.
type SavePortsBulkResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SavePortsBulkResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SavePortsBulkResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SavePortsBulkResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SavePortsBulkResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SavePortsBulkResponseValidationError) ErrorName() string {
	return "SavePortsBulkResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SavePortsBulkResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSavePortsBulkResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SavePortsBulkResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SavePortsBulkResponseValidationError{}

// Validate checks the field values on PortEntity with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *PortEntity) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetPortID()) < 1 {
		return PortEntityValidationError{
			field:  "PortID",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		return PortEntityValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetCode()) < 1 {
		return PortEntityValidationError{
			field:  "Code",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetCountry()) < 1 {
		return PortEntityValidationError{
			field:  "Country",
			reason: "value length must be at least 1 runes",
		}
	}

	// no validation rules for Province

	if utf8.RuneCountInString(m.GetCity()) < 1 {
		return PortEntityValidationError{
			field:  "City",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetTimezone()) < 1 {
		return PortEntityValidationError{
			field:  "Timezone",
			reason: "value length must be at least 1 runes",
		}
	}

	return nil
}

// PortEntityValidationError is the validation error returned by
// PortEntity.Validate if the designated constraints aren't met.
type PortEntityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PortEntityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PortEntityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PortEntityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PortEntityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PortEntityValidationError) ErrorName() string { return "PortEntityValidationError" }

// Error satisfies the builtin error interface
func (e PortEntityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPortEntity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PortEntityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PortEntityValidationError{}
